name: Backlog Issue Form
description: Create an Issue
title: "Backlog: "
projects: Test Assessment
milestone: 7 
body:
  - type: markdown
    attributes:
      value: |
        This is the Issue template! The values you add will be converted to a properly formatted Issue for the SNWG Assessment Project.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add two to three sentences that explain the context of this issue and what it will achieve.
      placeholder: Questions to consider when completing this section...
        - What is the motivation for this issue? 
        - Is there any needed background knowledge that would be helpful to the assignee? 
        - Is there a specific requestor for this issue? 
        - Are there time constraints?
        - What are the possible steps to completion? 
        - Who are the anticipated assignees? 
        - What problem will this issue solve?  
    validations:
      required: true
  - type: textarea
    id: Examples
    attributes:
      label: Examples
      description: if applicable, include examples of work that the issue will result in or use in development.
      placeholder: This type of document is what I am looking for...
    validations:
      required: false
  - type: textarea
    id: deliverable
    attributes:
      label: Deliverable
      description: Acceptance Criteria in the form of a tasklist. Once the issue has been created, individual tasks can be converted to issues if needed. 
      value: "- [ ] "
    validations:
      required: true
  - type: textarea
    id: implementation-considerations
    attributes:
      label: Implementation Blockers or Dependencies
      description: |
        Points that need to be considered when developing this feature/writing this doc
      placeholder: Why have you selected multiple quarters? What other organizations or resources does this issue depend on to be completed?
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Related Issues
      description: |
        Add cards on which this issue depends
        Github automatically provides a list of possible issues if you start by typing a `#`
      placeholder: depends on
    validations:
      required: false
