name: Issue
description: Create an Issue
title: M#Q#(TaskA.Subtask1): ISSUE TITLE
projects: Test Assessment
body:
  - type: markdown
    attributes:
      value: |
        This is the Issue template! The values you add will be converted to a properly formatted Issue for the Test Assessment Project.
  - type: dropdown
    id: Milestones
    attributes:
      label: Milestone
      description: What Milestone does this issue apply to? If issue is unrelated to previously listed Milestones, select External Work Request and provide full details and justification.
      options:
        - M1 (Develop and administer Asana)
        - M2 (Develop and administer the Report Generation Tool (RGT))
        - M3 (Support tri-agency SNWG assessment teams)
        - M4 (Contribute to NASAs OMB presentation)
        - M5 (Support NASAs SNWG principal)
        - M6 (Conduct lessons learned retrospective)
        - Backlog
        - External Work Request
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Quarter
    attributes:
      label: Quarter
      description: What Quarter does this issue apply to? If selecting multiple quarters, please include the expected task breakdown across quarters in your task description or implementation considerations. 
      multiple: true
      options:
        - Q1 (1 Oct to 31 Dec)
        - Q2 (1 Jan to 31 Mar)
        - Q3 (1 Apr to 30 Jun)
        - Q4 (1 Jul to 30 Sep)
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add two to three sentences that explain the context of this issue and what it will achieve.
      placeholder: your text goes here
    validations:
      required: true
  - type: textarea
    id: deliverable
    attributes:
      label: Deliverable
      description: What will be shown to to team to demonstrate acceptance criteria are complete
      placeholder: Acceptance Criteria in the form of a tasklist. Once the issue has been created, individual tasks can be converted to issues if needed. 
    validations:
      required: true
  - type: textarea
    id: implementation-considerations
    attributes:
      label: Implementation Blockers or Dependencies
      description: |
        Points that need to be considered when developing this feature/writing this doc
      placeholder: Why have you selected multiple quarters? What other organizations or resources does this issue depend on to be completed?
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Related Issues
      description: |
        Add cards on which this issue depends
        Github automatically provides a list of possible issues if you start by typing a `#`
      placeholder: depends on
    validations:
      required: false
