name: Issue
description: Create an Issue
title: "ADD THE ISSUE TITLE HERE"
projects: Test Assessment
body:
  - type: markdown
    attributes:
      value: |
        This is the Issue template! The values you add will be converted to a properly formatted Issue.
  - type: dropdown
    id: Milestones
    attributes:
      label: What Milestone does this issue apply to?
      options:
        - M1 (description)
        - M2 (description)
        - M3 (description)
        - M4 (description)
        - M5 (description)
        - M6 (description)
        - Backlog
        - External Work Request
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Quarter
    attributes:
      label: What Quarter does this issue apply to? If selecting multiple quarters, please include the expected task breakdown across quarters in your task description or implementation considerations. 
      multiple: true
      options:
        - Q1 (1 Oct to 31 Dec)
        - Q2 (1 Jan to 31 Mar)
        - Q3 (1 Apr to 30 Jun)
        - Q4 (1 Jul to 30 Sep)
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add two to three sentences that explain the context of this issue and what it will achieve.
      placeholder: your text goes here
    validations:
      required: true
  - type: textarea
    id: deliverable
    attributes:
      label: Deliverable
      description: What will be shown to to team to demonstrate acceptance criteria are complete
      placeholder: your tasklist goes here
    validations:
      required: true
  - type: textarea
    id: implementation-considerations
    attributes:
      label: Implementation Blockers or Dependencies
      description: |
        Points that need to be considered when developing this feature/writing this doc
      value: "- type your first consideration here"
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Related Issues
      description: |
        Add cards on which this issue depends
        Github automatically provides a list of possible issues if you start by typing a `#`
      placeholder: depends on
    validations:
      required: false
