name: Assign Backlog Issues to Milestone 7

on:
  issues:
    types:
      - opened

jobs:
  assign_to_backlog_milestone:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if issue title contains "Backlog:"
        id: check_title
        run: echo ::set-output name=contains_backlog::$(echo "${{ github.event.issue.title }}" | grep -c "Backlog:")

      - name: Assign to Milestone 7 (Backlog)
        if: steps.check_title.outputs.contains_backlog == '1'
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          
          echo "Assigning issue $ISSUE_NUMBER to Milestone 7 (Backlog)"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"milestone\": 7}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER"
