name: Assign Backlog Milestone on Status Change

on:
  project_card:
    types:
      - moved

jobs:
  assign_backlog_milestone:
    runs-on: ubuntu-latest

    steps:
      - name: Check if card moved to "Backlog" column
        id: check_card_column
        run: |
          card_column_name="${{ github.event.project_card.column_name }}"
          if [[ $card_column_name == "Backlog" ]]; then
            echo "::set-output name=assign_milestone::true"
          else
            echo "::set-output name=assign_milestone::false"
          fi

      - name: Assign Issue to Milestone
        if: steps.check_card_column.outputs.assign_milestone == 'true'
        run: |
          token="${{ secrets.GITHUB_TOKEN }}"
          repo="${{ github.repository }}"
          issue_number="${{ github.event.project_card.content_url | split('/') | last }}"
          milestone="Backlog"

          curl -X POST -H "Authorization: token $token" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo/issues/$issue_number/milestones/$milestone"
