name: Assign Backlog Issues to Milestone

on:
  issues:
    types:
      - opened

jobs:
  assign_backlog_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue title contains Backlog:
        id: check_issue_title
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ $issue_title == Backlog: ]]; then
            echo "::set-output name=assign_issue::true"
          else
            echo "::set-output name=assign_issue::false"
          fi

      - name: Assign Issue to Milestone
        if: steps.check_issue_title.outputs.assign_issue == 'true'
        run: |
          token="${{ secrets.GITHUB_TOKEN }}"
          repo="${{ github.repository }}"
          issue_number="${{ github.event.issue.number }}"
          milestone=Backlog

          curl -X POST -H "Authorization: token $token" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo/issues/$issue_number/milestones/$milestone"
