name: Update Project Card Status

on:
  issues:
    types:
      - edited

jobs:
  update_project_card_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue milestone is Backlog
        id: check_milestone
        run: |
          issue_milestone="${{ github.event.changes.milestone.from }}"
          if [[ $issue_milestone == Backlog ]]; then
            echo "::set-output name=update_project_card::true"
          else
            echo "::set-output name=update_project_card::false"
          fi

      - name: Update Project Card Status
        if: steps.check_milestone.outputs.update_project_card == 'true'
        run: |
          token="${{ secrets.GITHUB_TOKEN }}"
          project_card_id="${{ github.event.issue.project_card_id }}"
          new_column_name="Backlog"

          curl -X POST -H "Authorization: token $token" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Content-Type: application/json" \
            -d '{
              "column_id": "'"$new_column_name"'"
            }' \
            "https://api.github.com/projects/columns/cards/$project_card_id/moves"
