name: Assign Milestones based on Keywords

on:
  issues:
    types:
      - opened

jobs:
  assign_to_milestone:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check issue title for keywords
        id: check_keywords
        run: |
          title="${{ github.event.issue.title }}"
          if [[ $title == *M1* ]]; then
            milestone_number=1
          elif [[ $title == *M2* ]]; then
            milestone_number=2
          elif [[ $title == *M3* ]]; then
            milestone_number=3     
          elif [[ $title == *M4* ]]; then
            milestone_number=5
          elif [[ $title == *M6* ]]; then
            milestone_number=7
          elif [[ $title == *Backlog* ]]; then
            milestone_number=7
          # Add more conditions for other keywords and milestones as needed
          else
            milestone_number=null
          fi
          echo ::set-output name=milestone_number::$milestone_number

      - name: Assign to Milestone
        if: steps.check_keywords.outputs.milestone_number != 'null'
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          MILESTONE_NUMBER=${{ steps.check_keywords.outputs.milestone_number }}
          
          echo "Assigning issue $ISSUE_NUMBER to Milestone $MILESTONE_NUMBER"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"milestone\": $MILESTONE_NUMBER}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER"
